/* Generated by wayland-scanner 1.25.0 */

#ifndef EXT_IDLE_NOTIFIER_V1_CLIENT_PROTOCOL_H
#define EXT_IDLE_NOTIFIER_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_ext_idle_notifier_v1 The ext_idle_notifier_v1 protocol
 * notify clients when users have been idle
 *
 * @section page_desc_ext_idle_notifier_v1 Description
 *
 * This protocol allows clients to be informed when a seat has been idle for
 * a specific timeout and when activity resumes again.
 *
 * @section page_ifaces_ext_idle_notifier_v1 Interfaces
 * - @subpage page_iface_ext_idle_notifier_v1 - idle notification manager
 * - @subpage page_iface_ext_idle_notification_v1 - idle notification instance
 * @section page_copyright_ext_idle_notifier_v1 Copyright
 * <pre>
 *
 * SPDX-FileCopyrightText: 2024-2026 The Wayland Authors
 * SPDX-License-Identifier: MIT
 * </pre>
 */
struct ext_idle_notification_v1;
struct ext_idle_notifier_v1;
struct wl_seat;

#ifndef EXT_IDLE_NOTIFIER_V1_INTERFACE
#define EXT_IDLE_NOTIFIER_V1_INTERFACE
/**
 * @page page_iface_ext_idle_notifier_v1 ext_idle_notifier_v1
 * @section page_iface_ext_idle_notifier_v1_desc Description
 * @section page_iface_ext_idle_notifier_v1_api API
 * See @ref iface_ext_idle_notifier_v1.
 */
/**
 * @defgroup iface_ext_idle_notifier_v1 The ext_idle_notifier_v1 interface
 */
extern const struct wl_interface ext_idle_notifier_v1_interface;
#endif
#ifndef EXT_IDLE_NOTIFICATION_V1_INTERFACE
#define EXT_IDLE_NOTIFICATION_V1_INTERFACE
/**
 * @page page_iface_ext_idle_notification_v1 ext_idle_notification_v1
 * @section page_iface_ext_idle_notification_v1_desc Description
 * @section page_iface_ext_idle_notification_v1_api API
 * See @ref iface_ext_idle_notification_v1.
 */
/**
 * @defgroup iface_ext_idle_notification_v1 The ext_idle_notification_v1 interface
 */
extern const struct wl_interface ext_idle_notification_v1_interface;
#endif

#define EXT_IDLE_NOTIFIER_V1_GET_IDLE_NOTIFICATION 0
#define EXT_IDLE_NOTIFIER_V1_DESTROY 1


/**
 * @ingroup iface_ext_idle_notifier_v1
 */
#define EXT_IDLE_NOTIFIER_V1_GET_IDLE_NOTIFICATION_SINCE_VERSION 1
/**
 * @ingroup iface_ext_idle_notifier_v1
 */
#define EXT_IDLE_NOTIFIER_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_ext_idle_notifier_v1 */
static inline void
ext_idle_notifier_v1_set_user_data(struct ext_idle_notifier_v1 *ext_idle_notifier_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) ext_idle_notifier_v1, user_data);
}

/** @ingroup iface_ext_idle_notifier_v1 */
static inline void *
ext_idle_notifier_v1_get_user_data(struct ext_idle_notifier_v1 *ext_idle_notifier_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) ext_idle_notifier_v1);
}

static inline uint32_t
ext_idle_notifier_v1_get_version(struct ext_idle_notifier_v1 *ext_idle_notifier_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) ext_idle_notifier_v1);
}

/**
 * @ingroup iface_ext_idle_notifier_v1
 */
static inline struct ext_idle_notification_v1 *
ext_idle_notifier_v1_get_idle_notification(struct ext_idle_notifier_v1 *ext_idle_notifier_v1, struct wl_seat *seat, uint32_t timeout)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) ext_idle_notifier_v1,
			 EXT_IDLE_NOTIFIER_V1_GET_IDLE_NOTIFICATION, &ext_idle_notification_v1_interface, wl_proxy_get_version((struct wl_proxy *) ext_idle_notifier_v1), 0, NULL, seat, timeout);

	return (struct ext_idle_notification_v1 *) id;
}

/**
 * @ingroup iface_ext_idle_notifier_v1
 */
static inline void
ext_idle_notifier_v1_destroy(struct ext_idle_notifier_v1 *ext_idle_notifier_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) ext_idle_notifier_v1,
			 EXT_IDLE_NOTIFIER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) ext_idle_notifier_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_ext_idle_notification_v1
 * @struct ext_idle_notification_v1_listener
 */
struct ext_idle_notification_v1_listener {
	/**
	 */
	void (*idled)(void *data,
		      struct ext_idle_notification_v1 *ext_idle_notification_v1);
	/**
	 */
	void (*resumed)(void *data,
			struct ext_idle_notification_v1 *ext_idle_notification_v1);
};

/**
 * @ingroup iface_ext_idle_notification_v1
 */
static inline int
ext_idle_notification_v1_add_listener(struct ext_idle_notification_v1 *ext_idle_notification_v1,
				      const struct ext_idle_notification_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) ext_idle_notification_v1,
				     (void (**)(void)) listener, data);
}

#define EXT_IDLE_NOTIFICATION_V1_DESTROY 0

/**
 * @ingroup iface_ext_idle_notification_v1
 */
#define EXT_IDLE_NOTIFICATION_V1_IDLED_SINCE_VERSION 1
/**
 * @ingroup iface_ext_idle_notification_v1
 */
#define EXT_IDLE_NOTIFICATION_V1_RESUMED_SINCE_VERSION 1

/**
 * @ingroup iface_ext_idle_notification_v1
 */
#define EXT_IDLE_NOTIFICATION_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_ext_idle_notification_v1 */
static inline void
ext_idle_notification_v1_set_user_data(struct ext_idle_notification_v1 *ext_idle_notification_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) ext_idle_notification_v1, user_data);
}

/** @ingroup iface_ext_idle_notification_v1 */
static inline void *
ext_idle_notification_v1_get_user_data(struct ext_idle_notification_v1 *ext_idle_notification_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) ext_idle_notification_v1);
}

static inline uint32_t
ext_idle_notification_v1_get_version(struct ext_idle_notification_v1 *ext_idle_notification_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) ext_idle_notification_v1);
}

/**
 * @ingroup iface_ext_idle_notification_v1
 */
static inline void
ext_idle_notification_v1_destroy(struct ext_idle_notification_v1 *ext_idle_notification_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) ext_idle_notification_v1,
			 EXT_IDLE_NOTIFICATION_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) ext_idle_notification_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifdef  __cplusplus
}
#endif

#endif
