# KartON LightDM GTK Greeter style
[greeter]
theme-name=Karton-LightDM
icon-theme-name=Adwaita
font-name=Noto Sans 11
cursor-theme-name=KartONCursorDark
cursor-theme-size=24
clock-format=%a, %d %b %H:%M
background=#101625
xft-antialias=true
xft-hintstyle=hintfull
xft-rgba=rgb
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
position=50%,center 50%,center
panel-position=top
user-background=false
